source_id: 1vbO2uR_nJv15Ev5LrcVaBl2FY0A37b3CHj1ABrQhaFA
sheets:
  - name: Sheet1
    regions:
      - name: students_info
        start: A1
        end: A38
        contains_headers: true
        types: string
      - name: Quizzes
        start: B1
        end: J38
        contains_headers: true
        types: float
        fill: true
      - name: Midterm Exam
        start: K1
        end: K38
        contains_headers: true
        types: float
        fill: true
      - name: Activities
        start: L1
        end: V38
        contains_headers: true
        types: float
        fill: true
      - name: Practical
        start: W1
        end: AC38
        contains_headers: true
        types: float
        fill: true
      - name: Labs
        start: AD1
        end: AL38
        contains_headers: true
        types: float
        fill: true