source_id: 162ebb1faecad44e5b329ed6130fc0a1bd2cd977
sheets:
  - name: Sheet1
    regions:
      - name: students_info
        start: A1
        end: A38
        contains_headers: true
        types: string
      - name: Quiz
        start: B1
        end: J38
        contains_headers: true
        types: float
        fill: true
      - name: Midterm Exam
        start: K1
        end: K38
        contains_headers: true
        types: float
        fill: true
      - name: Activities
        start: L1
        end: V38
        contains_headers: true
        types: float
        fill: true
      - name: Practical
        start: W1
        end: AC38
        contains_headers: true
        types: float
        fill: true
      - name: Labs
        start: AD1
        end: AL38
        contains_headers: true
        types: float
        fill: true